<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNjffxnP\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNjffxnP/srcProdProjectContainer.php') {
    touch(__DIR__.'/ContainerNjffxnP.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\ContainerNjffxnP\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \ContainerNjffxnP\srcProdProjectContainer(array(
    'container.build_hash' => 'NjffxnP',
    'container.build_id' => 'c1c146e7',
    'container.build_time' => 1522944690,
));
