<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9VTPCEx\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9VTPCEx/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container9VTPCEx.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container9VTPCEx\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container9VTPCEx\srcDevDebugProjectContainer(array(
    'container.build_hash' => '9VTPCEx',
    'container.build_id' => 'b074c566',
    'container.build_time' => 1520272677,
));
